### ISSUE TITLE
Suggestion: Multiple restart Passwords, to distinguish who triggered a restart

### ISSUE THREAD

**Issue by RustyXXL** [Dateranoth/ConanExilesServerUtility#11]
We talked in steam about it. ;)

**Comment by Dateranoth** [comment]
@RustyXXL

I thought about how to implement this and I had this idea. It would be an easy implementation. 

You could enter multiple passwords in this format:
user1_pass1,user2_pass2 etc. 

Each password would be separated by a comma and the user part would be optional. The remote user would enter the entire string ( user1_pass1 ) . Any of the user_pass combinations would restart the server, and if it was used the user part would be logged to tell you who restarted the server. 

Only real down side to this is you will not be able to use _ or , in passwords because I will be using those delimiters to parse the strings.

**Comment by RustyXXL** [comment]
Well, technically speaking you might be able to add escaping, if you really want to be able to use those characters. Depends on the string manipulation capabilities of autoit. ;)
ie:
```
\\ = \
\_ = _
\, = ,
```

But I don't think that it would really be a problem, and having to explain the escaping additionally to the format of the user/password list might simply make it not worth it. In the end kiss: keep it simple, stupid. ;)

So I think your suggestion would be perfectly fine.

**Comment by Dateranoth** [comment]
It would be possible to add escaping or just use two characters to define the break. But, in this case I am going to have to agree with KISS.

**Comment by Dateranoth** [comment]
@RustyXXL 
I have released a beta with the features we discussed. I have not pulled it to master yet or had time to fully test  it.
https://github.com/Dateranoth/ConanExilesServerUtility/releases/tag/2.8.5-beta

**Comment by RustyXXL** [comment]
We are using the 2.8.5 beta, and everythign we tested so far seems to work. We still aren't using Discord, so no feedback there, but we have 5 or 6 restart users, and it worked so far.
I think this can be closed for now.
