### ISSUE TITLE
Not clicking past Steam .dll popups

### ISSUE THREAD

**Issue by gabrielluis516** [Dateranoth/ConanExilesServerUtility#35]
I have not yet found a consistent reason for this yet. my VM has been running for days without any changes to settings or programs running and sometimes on a server restart it will click through them just fine and others it won't and my server won't be restarted. This is creating an issue for players on my server, as sometimes the server will be down for hours before I realize what's happened. 

Any fix or workaround?

**Comment by Dateranoth** [comment]
It's possible that the pop ups are taking longer than normal to show up ( I only wait 5 seconds each) Or possibly they are a different window title?  It should have "Entry Point Not Found" in the title. 

If you are running on a VM and don't need steam running in the background then the simple solution is to close steam while the server is running and the pop ups won't show up. 

Otherwise the only real solution I can offer is to increase the time the script waits for the window to show up.  This will delay the server start, but it's better than not starting at all.

**Comment by Dateranoth** [comment]
Going to close unless you report further trouble. If you think the delay needs to be longer I can push it before the final release of the next update.
