### ISSUE TITLE
Server not showing up

### ISSUE THREAD

**Issue by Serph91P** [Dateranoth/ConanExilesServerUtility#39]
Hello did everything you said in the instructions but the server is not showing up in the server browser.
as far as i know you dont have to set the Server name etc in the server startup anymore?

**Comment by smooreace** [comment]
This utility has nothing to do with connectivity. You either configured the server wrong or didnt manage ports properly

**Comment by Serph91P** [comment]
hi i used the same config file is used before i used this utility. i realy dont know why its not working properly. well it is working but the server is not showing up.

**Comment by Dateranoth** [comment]
smooreace is correct. The utility would not directly cause it to show or not show in the server browser. 

The only option I can think of being a problem is the multihome option. Off it will bind to all IPs. On it will bind to the IP you set in the INI. I would try it off first. If that doesn’t work set it to ON and make sure the IP you entered is your computers IP address and not 127.0.0.1

If you want to send me your configuration INI I can take a look. 

Otherwise, you are probably best off looking for help on the Conan forums or you could try Conan Admins United on Discord. They are a helpful group. https://discord.gg/aA3BA5P

I believe there is a way to directly connect to the server while you try to figure it out. 

Sorry I could not be anymore help.

**Comment by Serph91P** [comment]
Hey,

got it working thanks guys. the multihome thingy did the trick ;)

**Comment by Dateranoth** [comment]
Awesome! Glad I could help. Let me know if you have any other problems with the Utility.

**Comment by Serph91P** [comment]
The Multihome thingy was the culprit thank you :)
